en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Company Name. All Rights Reserved. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "Site Title"
  params:
    description: "Site Description"
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/example-page/"
    ### calls to action ###
    main_cta:
      text: "Join"
      link: "/example-page/"
    footer_cta:
      text: "Join us"
      link: "/example-page/"
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "/example-page/"
      weight: 1
    - identifier: "child-1"
      name: "Example Child Page"
      url: "/example-page/"
      weight: 1
      post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
      parent: "about"
    - identifier: "child-2"
      name: "Example Child Page"
      url: "/example-page/"
      weight: 2
      post: "Aenean commodo ligula get dolor. Aenean massa."
      parent: "about"
    - identifier: "child-3"
      name: "Example Child Page"
      url: "/example-page/"
      weight: 3
      post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "about"
    - identifier: "example"
      name: "Example"
      url: "/example-page/"
      weight: 2
    - identifier: "example-1"
      name: "Example Child Page"
      url: "/example-page/"
      weight: 1
      post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
      parent: "example"
    - identifier: "example-2"
      name: "Example Child Page"
      url: "/example-page/"
      weight: 2
      post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "example"
    - identifier: "example-3"
      name: "Example Child Page"
      url: "/example-page/"
      weight: 3
      post: "Aenean commodo ligula get dolor. Aenean massa. "
      parent: "example"
    - identifier: "demo-page"
      name: "Demo Page"
      url: "/demo-page/"
      weight: 3
    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 4
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 5
es:
  languageName: Spanish
  contentDir: content/es
  weight: 2
  title: "Título del Sitio"
  params:
    description: "Descripción del Sitio"
  menu:
    main:
    - identifier: "about"
      name: "Acerca de"
      url: "/example-page/"
      weight: 1
    - identifier: "child-1"
      name: "Página Hija de Ejemplo"
      url: "/example-page/"
      weight: 1
      parent: "about"
    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 3
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 2
